name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        if: ${{ !github.event.release.prerelease }}
        run: curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"

      - name: Deploy to beta
        if: ${{ github.event.release.prerelease }}
        run: curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_BETA }}"
